Imports System.Data.SqlClient
Imports Converter10.Njc.N3Lib.Utys
Imports System.Collections.Generic
Imports Microsoft.Office.Interop    'Excelファイル操作のため追加
Imports Converter10.Njc.Common

Namespace Njc.Repository

#Region "送金ルール基本情報"

    Public Class Bk_kanri_Repository

        Public Class SubConv
            Implements IConv

            ''' <summary>
            ''' 【抽出クエリ】
            ''' </summary>
            ''' <returns></returns>
            ''' <remarks></remarks>
            Function Get_UseQry(ByRef sortstr As String) As String Implements IConv.Get_UseQry

                Dim tmp_sql As String = ""

                sortstr = "[物件No],[部屋No],[送金ルール管理No]"

                'tmp_sql = tmp_sql & " SELECT "
                'tmp_sql = tmp_sql & " 	 bk_no AS [物件No] "
                'tmp_sql = tmp_sql & " 	,'' AS [部屋No] "
                'tmp_sql = tmp_sql & " 	,kn_no AS [送金ルール管理No] "
                'tmp_sql = tmp_sql & " 	,1 AS [一所有形態区分-棟/区分] "
                'tmp_sql = tmp_sql & " 	,start_ym AS [送金ルール適用開始日] "
                'tmp_sql = tmp_sql & " 	,end_ym AS [送金ルール適用終了日] "
                'tmp_sql = tmp_sql & " 	,kn_kei AS [管理形態] "
                'tmp_sql = tmp_sql & " 	,'' AS [一括借上 一部管理] "
                'tmp_sql = tmp_sql & " 	,CASE "
                'tmp_sql = tmp_sql & " 		WHEN sq_kanri_ky = 0 THEN 1 "
                'tmp_sql = tmp_sql & " 		WHEN sq_kanri_ky = 1 THEN 0 "
                'tmp_sql = tmp_sql & " 	 END AS [仲介物件 - 新規契約業務] "
                'tmp_sql = tmp_sql & " 	,CASE "
                'tmp_sql = tmp_sql & " 		WHEN sq_kanri_ko = 0 THEN 1 "
                'tmp_sql = tmp_sql & " 		WHEN sq_kanri_ko = 1 THEN 0 "
                'tmp_sql = tmp_sql & " 	 END AS [仲介物件 - 契約更新業務]	 "
                'tmp_sql = tmp_sql & " 	,CASE "
                'tmp_sql = tmp_sql & " 		WHEN sq_kanri_kai = 0 THEN 1 "
                'tmp_sql = tmp_sql & " 		WHEN sq_kanri_kai = 1 THEN 0 "
                'tmp_sql = tmp_sql & " 	 END AS [仲介物件 - 解約業務]	 "
                'tmp_sql = tmp_sql & " 	,CASE "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn1 = -2 THEN 1 "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn1 = -1 THEN 2 "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn1 = 0 THEN 3 "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn1 = 1 THEN 4 "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn1 = 2 THEN 5 "
                'tmp_sql = tmp_sql & " 		ELSE -1 "
                'tmp_sql = tmp_sql & " 	 END AS [送金日決定方法1 - 該当年月] "
                'tmp_sql = tmp_sql & " 	,sime1 AS [送金日決定方法1 - 締日] "
                'tmp_sql = tmp_sql & " 	,CASE "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn1 = 0 THEN 1 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn1 = 1 THEN 2 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn1 = 2 THEN 3 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn1 = 3 THEN 4 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn1 = 4 THEN 5 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn1 = 5 THEN 6 "
                'tmp_sql = tmp_sql & " 		ELSE -1 "
                'tmp_sql = tmp_sql & " 	 END AS [送金日決定方法1 - 送金月] "
                'tmp_sql = tmp_sql & " 	,so_dd1 AS [送金日決定方法1 - 送金締日] "
                'tmp_sql = tmp_sql & " 	,CASE "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn2 = -2 THEN 1 "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn2 = -1 THEN 2 "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn2 = 0 THEN 3 "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn2 = 1 THEN 4 "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn2 = 2 THEN 5 "
                'tmp_sql = tmp_sql & " 		ELSE -1 "
                'tmp_sql = tmp_sql & " 	 END AS [送金日決定方法2 - 該当年月] "
                'tmp_sql = tmp_sql & " 	,sime2 AS [送金日決定方法2 - 締日] "
                'tmp_sql = tmp_sql & " 	,CASE "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn2 = 0 THEN 1 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn2 = 1 THEN 2 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn2 = 2 THEN 3 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn2 = 3 THEN 4 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn2 = 4 THEN 5 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn2 = 5 THEN 6 "
                'tmp_sql = tmp_sql & " 		ELSE -1 "
                'tmp_sql = tmp_sql & " 	 END AS [送金日決定方法2 - 送金月] "
                'tmp_sql = tmp_sql & " 	,so_dd2 AS [送金日決定方法2 - 送金締日] "
                'tmp_sql = tmp_sql & " 	,CASE "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn3 = -2 THEN 1 "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn3 = -1 THEN 2 "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn3 = 0 THEN 3 "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn3 = 1 THEN 4 "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn3 = 2 THEN 5 "
                'tmp_sql = tmp_sql & " 		ELSE -1 "
                'tmp_sql = tmp_sql & " 	 END AS [送金日決定方法3 - 該当年月] "
                'tmp_sql = tmp_sql & " 	,sime3 AS [送金日決定方法3 - 締日] "
                'tmp_sql = tmp_sql & " 	,CASE "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn3 = 0 THEN 1 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn3 = 1 THEN 2 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn3 = 2 THEN 3 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn3 = 3 THEN 4 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn3 = 4 THEN 5 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn3 = 5 THEN 6 "
                'tmp_sql = tmp_sql & " 		ELSE -1 "
                'tmp_sql = tmp_sql & " 	 END AS [送金日決定方法3 - 送金月] "
                'tmp_sql = tmp_sql & " 	,so_dd3 AS [送金日決定方法3 - 送金締日] "
                'tmp_sql = tmp_sql & " 	,CASE "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn4 = -2 THEN 1 "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn4 = -1 THEN 2 "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn4 = 0 THEN 3 "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn4 = 1 THEN 4 "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn4 = 2 THEN 5 "
                'tmp_sql = tmp_sql & " 		ELSE -1 "
                'tmp_sql = tmp_sql & " 	 END AS [送金日決定方法4 - 該当年月] "
                'tmp_sql = tmp_sql & " 	,sime4 AS [送金日決定方法4 - 締日] "
                'tmp_sql = tmp_sql & " 	,CASE "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn4 = 0 THEN 1 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn4 = 1 THEN 2 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn4 = 2 THEN 3 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn4 = 3 THEN 4 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn4 = 4 THEN 5 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn4 = 5 THEN 6 "
                'tmp_sql = tmp_sql & " 		ELSE -1 "
                'tmp_sql = tmp_sql & " 	 END AS [送金日決定方法4 - 送金月] "
                'tmp_sql = tmp_sql & " 	,so_dd4 AS [送金日決定方法4 - 送金締日] "
                'tmp_sql = tmp_sql & " 	,CASE "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn5 = -2 THEN 1 "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn5 = -1 THEN 2 "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn5 = 0 THEN 3 "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn5 = 1 THEN 4 "
                'tmp_sql = tmp_sql & " 		WHEN sime_kbn5 = 2 THEN 5 "
                'tmp_sql = tmp_sql & " 		ELSE -1 "
                'tmp_sql = tmp_sql & " 	 END AS [送金日決定方法5 - 該当年月] "
                'tmp_sql = tmp_sql & " 	,sime5 AS [送金日決定方法5 - 締日] "
                'tmp_sql = tmp_sql & " 	,CASE "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn5 = 0 THEN 1 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn5 = 1 THEN 2 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn5 = 2 THEN 3 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn5 = 3 THEN 4 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn5 = 4 THEN 5 "
                'tmp_sql = tmp_sql & " 		WHEN som_kbn5 = 5 THEN 6 "
                'tmp_sql = tmp_sql & " 		ELSE -1 "
                'tmp_sql = tmp_sql & " 	 END AS [送金日決定方法5 - 送金月] "
                'tmp_sql = tmp_sql & " 	,so_dd5 AS [送金日決定方法5 - 送金締日] "
                'tmp_sql = tmp_sql & " 	,1 AS [送金先単独/複数指定] "
                'tmp_sql = tmp_sql & " 	,sokin_kbn AS [送金固定額使用フラグ] "
                'tmp_sql = tmp_sql & " 	,[金額指定口座数]  AS [送金固定数]	/*物件送金情報から取得した金額指定の口座数をセット*/ "
                'tmp_sql = tmp_sql & " 	,1 AS [均等案分フラグ] "
                'tmp_sql = tmp_sql & " 	,[端数受取口座行No] AS [端数受取先]	/*物件送金情報から取得した端数受取口座の口座行Noをセット*/ "
                'tmp_sql = tmp_sql & " 	,0 AS [送金額案分端数調整フラグ]	/*デフォルト値確認*/ "
                'tmp_sql = tmp_sql & " 	,1 AS [一括借上 物件毎/部屋毎] "
                'tmp_sql = tmp_sql & " 	,karigaku AS [一括借上 物件毎設定額] "
                'tmp_sql = tmp_sql & " 	,0 AS [一括借上 免責期間の設定フラグ] "
                'tmp_sql = tmp_sql & " 	,0 AS [一括借上 免責期間(解約翌月から何カ月)] "
                'tmp_sql = tmp_sql & " 	,kn_tesu_kbn AS [管理手数料区分] "
                'tmp_sql = tmp_sql & " 	,1 AS [管理手数料徴収区分] "
                'tmp_sql = tmp_sql & " 	,0 AS [管理手数料 例外：契約金は対象外とする] "
                'tmp_sql = tmp_sql & " 	,0 AS [管理手数料 例外：解約金は対象外とする] "
                'tmp_sql = tmp_sql & " 	,'' AS [管理手数料定額区分] "
                'tmp_sql = tmp_sql & " 	,CASE "
                'tmp_sql = tmp_sql & " 		WHEN kn_tesu_kbn = 2 THEN tesu_gaku "
                'tmp_sql = tmp_sql & " 		ELSE NULL "
                'tmp_sql = tmp_sql & " 	 END AS [部屋毎定額 - 全部屋一律管理手数料] "
                'tmp_sql = tmp_sql & " 	,CASE "
                'tmp_sql = tmp_sql & " 		WHEN yobi_si1 = 1 THEN 0 "
                'tmp_sql = tmp_sql & " 		WHEN yobi_si1 = 3 THEN 1 "
                'tmp_sql = tmp_sql & " 	 ELSE 0 "
                'tmp_sql = tmp_sql & " 	 END AS [部屋毎定額 - 部屋毎日割りフラグ] "
                'tmp_sql = tmp_sql & " 	,CASE "
                'tmp_sql = tmp_sql & " 		WHEN kn_tesu_kbn = 3 THEN tesu_gaku "
                'tmp_sql = tmp_sql & " 		ELSE NULL "
                'tmp_sql = tmp_sql & " 	 END AS [物件毎定額 - 物件管理手数料]	 "
                'tmp_sql = tmp_sql & " 	,tesu_zei AS [管理手数料 消費税適用フラグ] "
                'tmp_sql = tmp_sql & " 	,'' AS [備考 - 基本情報] "
                'tmp_sql = tmp_sql & " 	,0 AS [支払明細書関連 - 同時契約の場合は代表する部屋を表示] "
                'tmp_sql = tmp_sql & " 	,0 AS [支払明細書関連 - 口座毎に支払明細書を作成1]		/*ヘッダー名が同一なので1、2で分けておく*/ "
                'tmp_sql = tmp_sql & " 	,-1 AS [支払明細書関連 - 口座毎に支払明細書を作成2]		/*ヘッダー名が同一なので1、2で分けておく*/ "
                'tmp_sql = tmp_sql & " 	,-1 AS [部屋毎一括借上額 - 入金項目No1] "
                'tmp_sql = tmp_sql & " 	,-1 AS [部屋毎一括借上額 - 入金項目No2] "
                'tmp_sql = tmp_sql & " 	,-1 AS [部屋毎一括借上額 - 入金項目No3] "
                'tmp_sql = tmp_sql & " 	,-1 AS [部屋毎一括借上額 - 入金項目No4] "
                'tmp_sql = tmp_sql & " 	,-1 AS [部屋毎一括借上額 - 入金項目No5] "
                'tmp_sql = tmp_sql & " 	,yobi_bt5 AS [管理手数料計算基準区分] "
                'tmp_sql = tmp_sql & " 	,0 AS [満額入金-送金フラグ] "
                'tmp_sql = tmp_sql & " 	,zuiji_sokin AS [仲介物件 - 随時送金] "
                'tmp_sql = tmp_sql & " 	,1 AS [一括借上 部屋毎一括借上額の計算方法] "
                'tmp_sql = tmp_sql & " 	,0 AS [一括借上 消費税適用フラグ] "
                'tmp_sql = tmp_sql & " 	/*,'' AS [内税フラグ]*/		/*タケツーカスタマイズ*/ "
                'tmp_sql = tmp_sql & " 	/*,'' AS [soymd_basis]*/	/*使用箇所不明*/ "
                'tmp_sql = tmp_sql & " FROM "
                'tmp_sql = tmp_sql & " ( "
                'tmp_sql = tmp_sql & " 	SELECT "
                'tmp_sql = tmp_sql & " 		 BKK.* "
                'tmp_sql = tmp_sql & " 		,HASUUUKETORIKOZANO.[端数受取口座行No] "
                'tmp_sql = tmp_sql & " 		,KINGAKSITEIKOZA.[金額指定口座数] "
                'tmp_sql = tmp_sql & " 	FROM bk_kanri AS BKK "
                'tmp_sql = tmp_sql & " 	LEFT JOIN "
                'tmp_sql = tmp_sql & " 		( "
                'tmp_sql = tmp_sql & " 			/*物件送金先情報から端数受取口座の行Noを取得する sta*/ "
                'tmp_sql = tmp_sql & " 			SELECT "
                'tmp_sql = tmp_sql & " 				 bk_no "
                'tmp_sql = tmp_sql & " 				,kn_no "
                'tmp_sql = tmp_sql & " 				,so_no "
                'tmp_sql = tmp_sql & " 				,sokoza_no "
                'tmp_sql = tmp_sql & " 				,[口座行No] AS [端数受取口座行No] "
                'tmp_sql = tmp_sql & " 			FROM "
                'tmp_sql = tmp_sql & " 			( "
                'tmp_sql = tmp_sql & " 				/*①比率指定のデータのうち、「代表」にチェックされているデータを取得*/ "
                'tmp_sql = tmp_sql & " 				SELECT * FROM "
                'tmp_sql = tmp_sql & " 				( "
                'tmp_sql = tmp_sql & " 					SELECT "
                'tmp_sql = tmp_sql & " 						 ROW_NUMBER()OVER(PARTITION BY bk_no,kn_no,so_no ORDER BY bk_no,kn_no,so_no,sokoza_no) AS [口座行No] "
                'tmp_sql = tmp_sql & " 						,* "
                'tmp_sql = tmp_sql & " 					FROM bk_sokin "
                'tmp_sql = tmp_sql & " 				) AS BKS "
                'tmp_sql = tmp_sql & " 				WHERE EXISTS "
                'tmp_sql = tmp_sql & " 					( "
                'tmp_sql = tmp_sql & " 						SELECT * FROM bk_kanri AS BKK "
                'tmp_sql = tmp_sql & " 						WHERE BKS.bk_no = BKK.bk_no "
                'tmp_sql = tmp_sql & " 						AND   BKS.kn_no = BKK.kn_no "
                'tmp_sql = tmp_sql & " 						AND   BKK.sokin_kbn = 0 "
                'tmp_sql = tmp_sql & " 						AND   BKS.daihyo = 1 "
                'tmp_sql = tmp_sql & " 					) "
                'tmp_sql = tmp_sql & " 				/*①比率指定のデータのうち、「代表」にチェックされているデータを取得*/ "
                'tmp_sql = tmp_sql & " 				UNION "
                'tmp_sql = tmp_sql & " 				/*②金額指定のデータのうち、金額が0円のデータを取得*/ "
                'tmp_sql = tmp_sql & " 				SELECT * FROM "
                'tmp_sql = tmp_sql & " 				( "
                'tmp_sql = tmp_sql & " 					SELECT "
                'tmp_sql = tmp_sql & " 						 ROW_NUMBER()OVER(PARTITION BY bk_no,kn_no,so_no ORDER BY bk_no,kn_no,so_no,sokoza_no) AS [口座行No] "
                'tmp_sql = tmp_sql & " 						,* "
                'tmp_sql = tmp_sql & " 					FROM bk_sokin "
                'tmp_sql = tmp_sql & " 				) AS BKS "
                'tmp_sql = tmp_sql & " 				WHERE EXISTS "
                'tmp_sql = tmp_sql & " 					( "
                'tmp_sql = tmp_sql & " 						SELECT * FROM bk_kanri AS BKK "
                'tmp_sql = tmp_sql & " 						WHERE BKS.bk_no = BKK.bk_no "
                'tmp_sql = tmp_sql & " 						AND   BKS.kn_no = BKK.kn_no "
                'tmp_sql = tmp_sql & " 						AND   BKK.sokin_kbn = 1 "
                'tmp_sql = tmp_sql & " 						AND   BKS.yobi_kn1 = 0 "
                'tmp_sql = tmp_sql & " 					) "
                'tmp_sql = tmp_sql & " 				/*②金額指定のデータのうち、金額が0円のデータを取得*/ "
                'tmp_sql = tmp_sql & " 			) AS VW "
                'tmp_sql = tmp_sql & " 			/*物件送金先情報から端数受取口座の行Noを取得する end*/ "
                'tmp_sql = tmp_sql & " 		) AS HASUUUKETORIKOZANO "
                'tmp_sql = tmp_sql & " 	ON  BKK.bk_no = HASUUUKETORIKOZANO.bk_no "
                'tmp_sql = tmp_sql & " 	AND BKK.kn_no = HASUUUKETORIKOZANO.kn_no "
                'tmp_sql = tmp_sql & " 	LEFT JOIN "
                'tmp_sql = tmp_sql & " 		( "
                'tmp_sql = tmp_sql & " 			/*物件送金先情報から金額指定されている口座数を取得する sta*/ "
                'tmp_sql = tmp_sql & " 			SELECT * FROM "
                'tmp_sql = tmp_sql & " 			( "
                'tmp_sql = tmp_sql & " 				SELECT "
                'tmp_sql = tmp_sql & " 					 bk_no "
                'tmp_sql = tmp_sql & " 					,kn_no "
                'tmp_sql = tmp_sql & " 					,so_no "
                'tmp_sql = tmp_sql & " 					,MAX([金額指定口座No]) AS [金額指定口座数] "
                'tmp_sql = tmp_sql & " 				FROM "
                'tmp_sql = tmp_sql & " 					( "
                'tmp_sql = tmp_sql & " 						SELECT "
                'tmp_sql = tmp_sql & " 							 ROW_NUMBER()OVER(PARTITION BY bk_no,kn_no,so_no ORDER BY bk_no,kn_no,so_no) AS [金額指定口座No] "
                'tmp_sql = tmp_sql & " 							,* "
                'tmp_sql = tmp_sql & " 						FROM bk_sokin "
                'tmp_sql = tmp_sql & " 					) AS BKS "
                'tmp_sql = tmp_sql & " 					WHERE EXISTS "
                'tmp_sql = tmp_sql & " 						( "
                'tmp_sql = tmp_sql & " 							SELECT * FROM bk_kanri AS BKK "
                'tmp_sql = tmp_sql & " 							WHERE BKS.bk_no = BKK.bk_no "
                'tmp_sql = tmp_sql & " 							AND   BKS.kn_no = BKK.kn_no "
                'tmp_sql = tmp_sql & " 							AND   BKK.sokin_kbn = 1 "
                'tmp_sql = tmp_sql & " 							AND   BKS.yobi_kn1 <> 0 "
                'tmp_sql = tmp_sql & " 						) "
                'tmp_sql = tmp_sql & " 				GROUP BY bk_no,kn_no,so_no "
                'tmp_sql = tmp_sql & " 			) AS VW "
                'tmp_sql = tmp_sql & " 			/*物件送金先情報から金額指定されている口座数を取得する end*/ "
                'tmp_sql = tmp_sql & " 		) AS KINGAKSITEIKOZA "
                'tmp_sql = tmp_sql & " 	ON  BKK.bk_no = KINGAKSITEIKOZA.bk_no "
                'tmp_sql = tmp_sql & " 	AND BKK.kn_no = KINGAKSITEIKOZA.kn_no "
                'tmp_sql = tmp_sql & " ) AS SORULEMOTO "

                '比率/金額指定取得方法を修正
                '送金固定数の取得方法修正


                '抽出データの改行文字列を除去する暫定処理
                Dim tmp_midheader As String = "[物件No],[部屋No],[送金ルール管理No],[一所有形態区分-棟/区分],[送金ルール適用開始日],[送金ルール適用終了日],[管理形態],[一括借上 一部管理],[仲介物件 - 新規契約業務],[仲介物件 - 契約更新業務],[仲介物件 - 解約業務],[送金日決定方法1 - 該当年月],[送金日決定方法1 - 締日],[送金日決定方法1 - 送金月],[送金日決定方法1 - 送金締日],[送金日決定方法2 - 該当年月],[送金日決定方法2 - 締日],[送金日決定方法2 - 送金月],[送金日決定方法2 - 送金締日],[送金日決定方法3 - 該当年月],[送金日決定方法3 - 締日],[送金日決定方法3 - 送金月],[送金日決定方法3 - 送金締日],[送金日決定方法4 - 該当年月],[送金日決定方法4 - 締日],[送金日決定方法4 - 送金月],[送金日決定方法4 - 送金締日],[送金日決定方法5 - 該当年月],[送金日決定方法5 - 締日],[送金日決定方法5 - 送金月],[送金日決定方法5 - 送金締日],[送金先単独/複数指定],[送金固定額使用フラグ],[送金固定数],[均等案分フラグ],[端数受取先],[送金額案分端数調整フラグ],[一括借上 物件毎/部屋毎],[一括借上 物件毎設定額],[一括借上 免責期間の設定フラグ],[一括借上 免責期間(解約翌月から何カ月)],[管理手数料区分],[管理手数料徴収区分],[管理手数料 例外：契約金は対象外とする],[管理手数料 例外：解約金は対象外とする],[管理手数料定額区分],[部屋毎定額 - 全部屋一律管理手数料],[部屋毎定額 - 部屋毎日割りフラグ],[物件毎定額 - 物件管理手数料],[管理手数料 消費税適用フラグ],[備考 - 基本情報],[支払明細書関連 - 同時契約の場合は代表する部屋を表示],[支払明細書関連 - 口座毎に支払明細書を作成1],[支払明細書関連 - 口座毎に支払明細書を作成2],[部屋毎一括借上額 - 入金項目No1],[部屋毎一括借上額 - 入金項目No2],[部屋毎一括借上額 - 入金項目No3],[部屋毎一括借上額 - 入金項目No4],[部屋毎一括借上額 - 入金項目No5],[管理手数料計算基準区分],[満額入金-送金フラグ],[仲介物件 - 随時送金],[一括借上 部屋毎一括借上額の計算方法],[一括借上 消費税適用フラグ]"
                Dim tmp_chgmidheader As String = EtcMethod.Get_FldnameAddReplaceMethod(tmp_midheader, True)
                '抽出データの改行文字列を除去する暫定処理

                'tmp_sql = tmp_sql & " SELECT * FROM "
                tmp_sql = tmp_sql & " SELECT " & tmp_chgmidheader & " FROM "
                tmp_sql = tmp_sql & " ( "
                tmp_sql = tmp_sql & " 	SELECT "
                tmp_sql = tmp_sql & " 		 bk_no AS [物件No] "
                tmp_sql = tmp_sql & " 		,'' AS [部屋No] "
                tmp_sql = tmp_sql & " 		,kn_no AS [送金ルール管理No] "
                tmp_sql = tmp_sql & " 		,1 AS [一所有形態区分-棟/区分] "
                tmp_sql = tmp_sql & " 		,start_ym AS [送金ルール適用開始日] "
                tmp_sql = tmp_sql & " 		/*2016.04.26 物件管理情報が最新以外の場合は送金ルール終了日を設定する chg sta*/ "
                tmp_sql = tmp_sql & " 		/* "
                tmp_sql = tmp_sql & " 		/*2016.04.14 送金ルール終了日を空にする (物件所有終了日に合わせるため) chg sta*/ "
                tmp_sql = tmp_sql & " 		/*,end_ym AS [送金ルール適用終了日]*/ "
                tmp_sql = tmp_sql & " 		,NULL AS [送金ルール適用終了日] "
                tmp_sql = tmp_sql & " 		/*2016.04.14 送金ルール終了日を空にする (物件所有終了日に合わせるため) chg end*/ "
                tmp_sql = tmp_sql & " 		*/ "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN 抽出用 = 1 THEN NULL "
                tmp_sql = tmp_sql & " 			ELSE end_ym "
                tmp_sql = tmp_sql & " 		 END AS [送金ルール適用終了日] "
                tmp_sql = tmp_sql & " 		/*2016.04.26 物件管理情報が最新以外の場合は送金ルール終了日を設定する chg end*/ "
                tmp_sql = tmp_sql & " 		,kn_kei AS [管理形態] "
                tmp_sql = tmp_sql & " 		,'' AS [一括借上 一部管理] "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN sq_kanri_ky = 0 THEN 1 "
                tmp_sql = tmp_sql & " 			WHEN sq_kanri_ky = 1 THEN 0 "
                tmp_sql = tmp_sql & " 		 END AS [仲介物件 - 新規契約業務] "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN sq_kanri_ko = 0 THEN 1 "
                tmp_sql = tmp_sql & " 			WHEN sq_kanri_ko = 1 THEN 0 "
                tmp_sql = tmp_sql & " 		 END AS [仲介物件 - 契約更新業務]	 "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN sq_kanri_kai = 0 THEN 1 "
                tmp_sql = tmp_sql & " 			WHEN sq_kanri_kai = 1 THEN 0 "
                tmp_sql = tmp_sql & " 		 END AS [仲介物件 - 解約業務]	 "
                tmp_sql = tmp_sql & " 		/*20160829 送金予定日デフォルト値設定 chg sta*/ "
                tmp_sql = tmp_sql & " 		/* "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn1 = -2 THEN 1 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn1 = -1 THEN 2 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn1 = 0 THEN 3 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn1 = 1 THEN 4 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn1 = 2 THEN 5 "
                tmp_sql = tmp_sql & " 			ELSE -1 "
                tmp_sql = tmp_sql & " 		 END AS [送金日決定方法1 - 該当年月] "
                tmp_sql = tmp_sql & " 		,sime1 AS [送金日決定方法1 - 締日] "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN som_kbn1 = 0 THEN 1 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn1 = 1 THEN 2 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn1 = 2 THEN 3 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn1 = 3 THEN 4 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn1 = 4 THEN 5 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn1 = 5 THEN 6 "
                tmp_sql = tmp_sql & " 			ELSE -1 "
                tmp_sql = tmp_sql & " 		 END AS [送金日決定方法1 - 送金月] "
                tmp_sql = tmp_sql & " 		,so_dd1 AS [送金日決定方法1 - 送金締日] "
                tmp_sql = tmp_sql & " 		*/ "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn1 = -2 THEN 1 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn1 = -1 THEN 2 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn1 = 0 THEN 3 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn1 = 1 THEN 4 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn1 = 2 THEN 5 "
                tmp_sql = tmp_sql & " 			ELSE 2 "
                tmp_sql = tmp_sql & " 		 END AS [送金日決定方法1 - 該当年月] "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN ISNULL(sime1,0) = 0 THEN 30 "
                tmp_sql = tmp_sql & " 			ELSE sime1 "
                tmp_sql = tmp_sql & " 		 END AS [送金日決定方法1 - 締日] "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN som_kbn1 = 0 THEN 1 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn1 = 1 THEN 2 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn1 = 2 THEN 3 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn1 = 3 THEN 4 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn1 = 4 THEN 5 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn1 = 5 THEN 6 "
                tmp_sql = tmp_sql & " 			ELSE 2 "
                tmp_sql = tmp_sql & " 		 END AS [送金日決定方法1 - 送金月] "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN ISNULL(so_dd1,0) = 0 THEN 10 "
                tmp_sql = tmp_sql & " 			ELSE so_dd1 "
                tmp_sql = tmp_sql & " 		 END AS [送金日決定方法1 - 送金締日] "
                tmp_sql = tmp_sql & " 		/*20160829 送金予定日デフォルト値設定 chg end*/ "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn2 = -2 THEN 1 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn2 = -1 THEN 2 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn2 = 0 THEN 3 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn2 = 1 THEN 4 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn2 = 2 THEN 5 "
                tmp_sql = tmp_sql & " 			ELSE -1 "
                tmp_sql = tmp_sql & " 		 END AS [送金日決定方法2 - 該当年月] "
                tmp_sql = tmp_sql & " 		,sime2 AS [送金日決定方法2 - 締日] "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN som_kbn2 = 0 THEN 1 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn2 = 1 THEN 2 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn2 = 2 THEN 3 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn2 = 3 THEN 4 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn2 = 4 THEN 5 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn2 = 5 THEN 6 "
                tmp_sql = tmp_sql & " 			ELSE -1 "
                tmp_sql = tmp_sql & " 		 END AS [送金日決定方法2 - 送金月] "
                tmp_sql = tmp_sql & " 		,so_dd2 AS [送金日決定方法2 - 送金締日] "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn3 = -2 THEN 1 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn3 = -1 THEN 2 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn3 = 0 THEN 3 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn3 = 1 THEN 4 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn3 = 2 THEN 5 "
                tmp_sql = tmp_sql & " 			ELSE -1 "
                tmp_sql = tmp_sql & " 		 END AS [送金日決定方法3 - 該当年月] "
                tmp_sql = tmp_sql & " 		,sime3 AS [送金日決定方法3 - 締日] "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN som_kbn3 = 0 THEN 1 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn3 = 1 THEN 2 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn3 = 2 THEN 3 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn3 = 3 THEN 4 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn3 = 4 THEN 5 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn3 = 5 THEN 6 "
                tmp_sql = tmp_sql & " 			ELSE -1 "
                tmp_sql = tmp_sql & " 		 END AS [送金日決定方法3 - 送金月] "
                tmp_sql = tmp_sql & " 		,so_dd3 AS [送金日決定方法3 - 送金締日] "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn4 = -2 THEN 1 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn4 = -1 THEN 2 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn4 = 0 THEN 3 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn4 = 1 THEN 4 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn4 = 2 THEN 5 "
                tmp_sql = tmp_sql & " 			ELSE -1 "
                tmp_sql = tmp_sql & " 		 END AS [送金日決定方法4 - 該当年月] "
                tmp_sql = tmp_sql & " 		,sime4 AS [送金日決定方法4 - 締日] "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN som_kbn4 = 0 THEN 1 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn4 = 1 THEN 2 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn4 = 2 THEN 3 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn4 = 3 THEN 4 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn4 = 4 THEN 5 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn4 = 5 THEN 6 "
                tmp_sql = tmp_sql & " 			ELSE -1 "
                tmp_sql = tmp_sql & " 		 END AS [送金日決定方法4 - 送金月] "
                tmp_sql = tmp_sql & " 		,so_dd4 AS [送金日決定方法4 - 送金締日] "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn5 = -2 THEN 1 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn5 = -1 THEN 2 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn5 = 0 THEN 3 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn5 = 1 THEN 4 "
                tmp_sql = tmp_sql & " 			WHEN sime_kbn5 = 2 THEN 5 "
                tmp_sql = tmp_sql & " 			ELSE -1 "
                tmp_sql = tmp_sql & " 		 END AS [送金日決定方法5 - 該当年月] "
                tmp_sql = tmp_sql & " 		,sime5 AS [送金日決定方法5 - 締日] "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN som_kbn5 = 0 THEN 1 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn5 = 1 THEN 2 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn5 = 2 THEN 3 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn5 = 3 THEN 4 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn5 = 4 THEN 5 "
                tmp_sql = tmp_sql & " 			WHEN som_kbn5 = 5 THEN 6 "
                tmp_sql = tmp_sql & " 			ELSE -1 "
                tmp_sql = tmp_sql & " 		 END AS [送金日決定方法5 - 送金月] "
                tmp_sql = tmp_sql & " 		,so_dd5 AS [送金日決定方法5 - 送金締日] "
                tmp_sql = tmp_sql & " 		,1 AS [送金先単独/複数指定] "
                tmp_sql = tmp_sql & " 		/*金額が全て0円の場合は比率扱いになりそのまま使用できないため取得方法を変更*/ "
                tmp_sql = tmp_sql & " 		/*,sokin_kbn AS [送金固定額使用フラグ]*/ "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN [金額指定時の金額合計] = 0 THEN 0 "
                tmp_sql = tmp_sql & " 			WHEN [金額指定時の金額合計] <> 0 THEN 1 "
                tmp_sql = tmp_sql & " 		 END AS [送金固定額使用フラグ] "
                tmp_sql = tmp_sql & " 		,[金額指定口座数]  AS [送金固定数]	/*物件送金情報から取得した金額指定の口座数をセット*/ "
                tmp_sql = tmp_sql & " 		/*20160929 均等案分フラグ取得処理の修正 -chg sta*/ "
                tmp_sql = tmp_sql & " 		/* "
                tmp_sql = tmp_sql & " 		/*2016.04.06 送金ルールの按分フラグ取得方法修正 -chg sta*/ "
                tmp_sql = tmp_sql & " 		/*,1 AS [均等案分フラグ]*/ "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN sokin_kbn = 0 THEN 0 "
                tmp_sql = tmp_sql & " 			ELSE 1 "
                tmp_sql = tmp_sql & " 		 END AS [均等案分フラグ] "
                tmp_sql = tmp_sql & " 		/*2016.04.06 送金ルールの按分フラグ取得方法修正 -chg end*/ "
                tmp_sql = tmp_sql & " 		*/ "
                tmp_sql = tmp_sql & " 		,0 AS [均等案分フラグ] "
                tmp_sql = tmp_sql & " 		/*20160929 均等案分フラグ取得処理の修正 -chg end*/ "
                tmp_sql = tmp_sql & " 		/*金額指定で固定口座が2つの場合は自動で残った口座に設定する*/ "
                tmp_sql = tmp_sql & " 		/*,[端数受取口座行No] AS [端数受取先]*/	/*物件送金情報から取得した端数受取口座の口座行Noをセット*/ "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN [金額指定口座数] = 2 THEN 3 "
                tmp_sql = tmp_sql & " 			ELSE [端数受取口座行No] "
                tmp_sql = tmp_sql & " 		 END AS [端数受取先] "
                tmp_sql = tmp_sql & " 		,0 AS [送金額案分端数調整フラグ]	/*デフォルト値確認*/ "
                tmp_sql = tmp_sql & " 		,1 AS [一括借上 物件毎/部屋毎] "
                tmp_sql = tmp_sql & " 		,karigaku AS [一括借上 物件毎設定額] "
                tmp_sql = tmp_sql & " 		,0 AS [一括借上 免責期間の設定フラグ] "
                tmp_sql = tmp_sql & " 		,0 AS [一括借上 免責期間(解約翌月から何カ月)] "
                tmp_sql = tmp_sql & " 		,kn_tesu_kbn AS [管理手数料区分] "
                tmp_sql = tmp_sql & " 		,1 AS [管理手数料徴収区分] "
                tmp_sql = tmp_sql & " 		,0 AS [管理手数料 例外：契約金は対象外とする] "
                tmp_sql = tmp_sql & " 		,0 AS [管理手数料 例外：解約金は対象外とする] "
                tmp_sql = tmp_sql & " 		,'' AS [管理手数料定額区分] "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN kn_tesu_kbn = 2 THEN tesu_gaku "
                tmp_sql = tmp_sql & " 			ELSE NULL "
                tmp_sql = tmp_sql & " 		 END AS [部屋毎定額 - 全部屋一律管理手数料] "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN yobi_si1 = 1 THEN 0 "
                tmp_sql = tmp_sql & " 			WHEN yobi_si1 = 3 THEN 1 "
                tmp_sql = tmp_sql & " 		 ELSE 0 "
                tmp_sql = tmp_sql & " 		 END AS [部屋毎定額 - 部屋毎日割りフラグ] "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN kn_tesu_kbn = 3 THEN tesu_gaku "
                tmp_sql = tmp_sql & " 			ELSE NULL "
                tmp_sql = tmp_sql & " 		 END AS [物件毎定額 - 物件管理手数料]	 "
                tmp_sql = tmp_sql & " 		,tesu_zei AS [管理手数料 消費税適用フラグ] "
                tmp_sql = tmp_sql & " 		,'' AS [備考 - 基本情報] "
                tmp_sql = tmp_sql & " 		,0 AS [支払明細書関連 - 同時契約の場合は代表する部屋を表示] "
                tmp_sql = tmp_sql & " 		,0 AS [支払明細書関連 - 口座毎に支払明細書を作成1]		/*ヘッダー名が同一なので1、2で分けておく*/ "
                tmp_sql = tmp_sql & " 		,-1 AS [支払明細書関連 - 口座毎に支払明細書を作成2]		/*ヘッダー名が同一なので1、2で分けておく*/ "
                tmp_sql = tmp_sql & " 		,-1 AS [部屋毎一括借上額 - 入金項目No1] "
                tmp_sql = tmp_sql & " 		,-1 AS [部屋毎一括借上額 - 入金項目No2] "
                tmp_sql = tmp_sql & " 		,-1 AS [部屋毎一括借上額 - 入金項目No3] "
                tmp_sql = tmp_sql & " 		,-1 AS [部屋毎一括借上額 - 入金項目No4] "
                tmp_sql = tmp_sql & " 		,-1 AS [部屋毎一括借上額 - 入金項目No5] "
                tmp_sql = tmp_sql & " 		,yobi_bt5 AS [管理手数料計算基準区分] "
                tmp_sql = tmp_sql & " 		,0 AS [満額入金-送金フラグ] "
                tmp_sql = tmp_sql & " 		,zuiji_sokin AS [仲介物件 - 随時送金] "
                tmp_sql = tmp_sql & " 		,1 AS [一括借上 部屋毎一括借上額の計算方法] "
                tmp_sql = tmp_sql & " 		,0 AS [一括借上 消費税適用フラグ] "
                tmp_sql = tmp_sql & " 		/*,'' AS [内税フラグ]*/		/*タケツーカスタマイズ*/ "
                tmp_sql = tmp_sql & " 		/*,'' AS [soymd_basis]*/	/*使用箇所不明*/ "
                tmp_sql = tmp_sql & " 	FROM "
                tmp_sql = tmp_sql & " 	( "
                tmp_sql = tmp_sql & " 		SELECT "
                tmp_sql = tmp_sql & " 			 BKK.* "
                tmp_sql = tmp_sql & " 			 /*2016.04.26 物件管理情報が最新以外の場合は送金ルール終了日を設定する add*/ "
                tmp_sql = tmp_sql & " 			,ROW_NUMBER()OVER(PARTITION BY BKK.bk_no ORDER BY BKK.kn_no DESC) AS 抽出用 "
                tmp_sql = tmp_sql & " 			,HASUUUKETORIKOZANO.[端数受取口座行No] "
                tmp_sql = tmp_sql & " 			,KINGAKSITEIKOZA.[金額指定口座数] "
                tmp_sql = tmp_sql & " 			,KINGAKGOKEI.[金額指定時の金額合計] "
                tmp_sql = tmp_sql & " 		FROM bk_kanri AS BKK "
                tmp_sql = tmp_sql & " 		LEFT JOIN "
                tmp_sql = tmp_sql & " 			( "
                tmp_sql = tmp_sql & " 				/*物件送金先情報から端数受取口座の行Noを取得する sta*/ "
                tmp_sql = tmp_sql & " 				SELECT "
                tmp_sql = tmp_sql & " 					 bk_no "
                tmp_sql = tmp_sql & " 					,kn_no "
                tmp_sql = tmp_sql & " 					,so_no "
                tmp_sql = tmp_sql & " 					,sokoza_no "
                tmp_sql = tmp_sql & " 					,[口座行No] AS [端数受取口座行No] "
                tmp_sql = tmp_sql & " 				FROM "
                tmp_sql = tmp_sql & " 				( "
                tmp_sql = tmp_sql & " 					/*①比率指定のデータのうち、「代表」にチェックされているデータを取得 sta*/ "
                tmp_sql = tmp_sql & " 					SELECT * FROM "
                tmp_sql = tmp_sql & " 					( "
                tmp_sql = tmp_sql & " 						SELECT "
                tmp_sql = tmp_sql & " 							 ROW_NUMBER()OVER(PARTITION BY bk_no,kn_no,so_no ORDER BY bk_no,kn_no,so_no,sokoza_no) AS [口座行No] "
                tmp_sql = tmp_sql & " 							,* "
                tmp_sql = tmp_sql & " 						FROM bk_sokin "
                tmp_sql = tmp_sql & " 					) AS BKS "
                tmp_sql = tmp_sql & " 					WHERE EXISTS "
                tmp_sql = tmp_sql & " 						( "
                tmp_sql = tmp_sql & " 							SELECT * FROM bk_kanri AS BKK "
                tmp_sql = tmp_sql & " 							WHERE BKS.bk_no = BKK.bk_no "
                tmp_sql = tmp_sql & " 							AND   BKS.kn_no = BKK.kn_no "
                tmp_sql = tmp_sql & " 							AND   BKK.sokin_kbn = 0 "
                tmp_sql = tmp_sql & " 							AND   BKS.daihyo = 1 "
                tmp_sql = tmp_sql & " 						) "
                tmp_sql = tmp_sql & " 					/*①比率指定のデータのうち、「代表」にチェックされているデータを取得 end*/ "
                tmp_sql = tmp_sql & " 					UNION "
                tmp_sql = tmp_sql & " 					/*②金額指定のデータのうち、金額が0円のデータを取得 sta*/ "
                tmp_sql = tmp_sql & " 					SELECT * FROM "
                tmp_sql = tmp_sql & " 					( "
                tmp_sql = tmp_sql & " 						SELECT "
                tmp_sql = tmp_sql & " 							 ROW_NUMBER()OVER(PARTITION BY bk_no,kn_no,so_no ORDER BY bk_no,kn_no,so_no,sokoza_no) AS [口座行No] "
                tmp_sql = tmp_sql & " 							,* "
                tmp_sql = tmp_sql & " 						FROM bk_sokin "
                tmp_sql = tmp_sql & " 					) AS BKS "
                tmp_sql = tmp_sql & " 					WHERE EXISTS "
                tmp_sql = tmp_sql & " 						( "
                tmp_sql = tmp_sql & " 							SELECT * FROM bk_kanri AS BKK "
                tmp_sql = tmp_sql & " 							WHERE BKS.bk_no = BKK.bk_no "
                tmp_sql = tmp_sql & " 							AND   BKS.kn_no = BKK.kn_no "
                tmp_sql = tmp_sql & " 							AND   BKK.sokin_kbn = 1 "
                tmp_sql = tmp_sql & " 							AND   BKS.yobi_kn1 = 0 "
                tmp_sql = tmp_sql & " 						) "
                tmp_sql = tmp_sql & " 					/*②金額指定のデータのうち、金額が0円のデータを取得 end*/ "
                tmp_sql = tmp_sql & " 				) AS VW "
                tmp_sql = tmp_sql & " 				/*物件送金先情報から端数受取口座の行Noを取得する end*/ "
                tmp_sql = tmp_sql & " 			) AS HASUUUKETORIKOZANO "
                tmp_sql = tmp_sql & " 		ON  BKK.bk_no = HASUUUKETORIKOZANO.bk_no "
                tmp_sql = tmp_sql & " 		AND BKK.kn_no = HASUUUKETORIKOZANO.kn_no "
                tmp_sql = tmp_sql & " 		LEFT JOIN "
                tmp_sql = tmp_sql & " 			( "
                tmp_sql = tmp_sql & " 				/*物件送金先情報から金額指定されている口座数を取得する sta*/ "
                tmp_sql = tmp_sql & " 				SELECT "
                tmp_sql = tmp_sql & " 					 bk_no "
                tmp_sql = tmp_sql & " 					,kn_no "
                tmp_sql = tmp_sql & " 					,so_no "
                tmp_sql = tmp_sql & " 					,MAX([金額指定口座No]) AS [金額指定口座数] "
                tmp_sql = tmp_sql & " 				FROM "
                tmp_sql = tmp_sql & " 				(			 "
                tmp_sql = tmp_sql & " 					SELECT "
                tmp_sql = tmp_sql & " 						 ROW_NUMBER()OVER(PARTITION BY bk_no,kn_no,so_no ORDER BY bk_no,kn_no,so_no) AS [金額指定口座No] "
                tmp_sql = tmp_sql & " 						,* "
                tmp_sql = tmp_sql & " 					FROM "
                tmp_sql = tmp_sql & " 					(		 "
                tmp_sql = tmp_sql & " 						SELECT * FROM bk_sokin WHERE yobi_kn1 <> 0 "
                tmp_sql = tmp_sql & " 					) AS VW "
                tmp_sql = tmp_sql & " 				) AS VW2 "
                tmp_sql = tmp_sql & " 				GROUP BY bk_no,kn_no,so_no "
                tmp_sql = tmp_sql & " 				/*物件送金先情報から金額指定されている口座数を取得する end*/ "
                tmp_sql = tmp_sql & " 			) AS KINGAKSITEIKOZA "
                tmp_sql = tmp_sql & " 		ON  BKK.bk_no = KINGAKSITEIKOZA.bk_no "
                tmp_sql = tmp_sql & " 		AND BKK.kn_no = KINGAKSITEIKOZA.kn_no "
                tmp_sql = tmp_sql & " 		LEFT JOIN "
                tmp_sql = tmp_sql & " 			( "
                tmp_sql = tmp_sql & " 				/*物件送金先情報から金額指定されている口座の金額合計を取得する sta*/ "
                tmp_sql = tmp_sql & " 				SELECT "
                tmp_sql = tmp_sql & " 					 bk_no "
                tmp_sql = tmp_sql & " 					,kn_no "
                tmp_sql = tmp_sql & " 					,so_no "
                tmp_sql = tmp_sql & " 					,SUM(yobi_kn1) AS [金額指定時の金額合計] "
                tmp_sql = tmp_sql & " 				FROM bk_sokin "
                tmp_sql = tmp_sql & " 				GROUP BY bk_no,kn_no,so_no "
                tmp_sql = tmp_sql & " 				/*物件送金先情報から金額指定されている口座の金額合計を取得する end*/ "
                tmp_sql = tmp_sql & " 			) AS KINGAKGOKEI "
                tmp_sql = tmp_sql & " 		ON  BKK.bk_no = KINGAKGOKEI.bk_no "
                tmp_sql = tmp_sql & " 		AND BKK.kn_no = KINGAKGOKEI.kn_no	 "
                tmp_sql = tmp_sql & " 	) AS SORULEMOTO "
                tmp_sql = tmp_sql & " 	/*20160520 送金ルール抽出内容の修正 add sta*/ "
                tmp_sql = tmp_sql & " 	/*V7では物件管理情報有り、物件送金情報無しの状態が許されているが、10では許されていないため予め除外しておく*/ "
                tmp_sql = tmp_sql & " 	/*20161107 自社物件の送金ルール作成方法修正 chg sta*/ "
                tmp_sql = tmp_sql & " 	/*自社物件は送金先情報が必要ないため、10に移行する際に送金先情報無しで送金ルールを作成するように修正*/ "
                tmp_sql = tmp_sql & " 	/* "
                tmp_sql = tmp_sql & " 	WHERE EXISTS "
                tmp_sql = tmp_sql & " 		( "
                tmp_sql = tmp_sql & " 			SELECT * FROM bk_sokin AS BKS WHERE SORULEMOTO.bk_no = BKS.bk_no AND SORULEMOTO.kn_no = BKS.kn_no "
                tmp_sql = tmp_sql & " 		) "
                tmp_sql = tmp_sql & " 	*/ "
                tmp_sql = tmp_sql & " 	WHERE kn_kei = 4 "
                tmp_sql = tmp_sql & " 	OR EXISTS "
                tmp_sql = tmp_sql & " 		( "
                tmp_sql = tmp_sql & " 			SELECT * FROM bk_sokin AS BKS WHERE SORULEMOTO.bk_no = BKS.bk_no AND SORULEMOTO.kn_no = BKS.kn_no "
                tmp_sql = tmp_sql & " 		) "
                tmp_sql = tmp_sql & " 	/*20161107 自社物件の送金ルール作成方法修正 chg end*/ "
                tmp_sql = tmp_sql & " 	/*20160520 送金ルール抽出内容の修正 add end*/ "
                tmp_sql = tmp_sql & " ) AS VW "

                Return tmp_sql

            End Function

            Public Function Chk_Data(ByVal tblname As String, ByVal keyvalue As String, ByVal list As List(Of String), ByVal hash_chkbefore As Hashtable, ByRef hash_chkafter As Hashtable, ByRef conditioncnt As Integer) As Boolean Implements IConv.Chk_Data

            End Function

            Public Sub Get_BaseKey(ByVal sqlcnnv10 As SqlConnection, ByVal tblname As String, ByRef list_basedata As List(Of String)) Implements IConv.Get_BaseKey

            End Sub

            Public Function Set_Vari(sqlcnnv10 As SqlConnection, filename As String, sheetname As String, ByRef midrowcnt As Integer, ByRef cvrowcnt As Integer, ByRef conditioncnt As Integer) As Boolean Implements IConv.Set_Vari

            End Function

            Public Sub Get_ExistData(sqlcnnv10 As SqlConnection, tblname As String, ByRef list_existdata As List(Of String)) Implements IConv.Get_ExistData

            End Sub

        End Class

    End Class

#End Region

#Region "送金ルール送金先情報"

    Public Class Bk_sokin_Repository

        Public Class SubConv
            Implements IConv

            ''' <summary>
            ''' 【抽出クエリ】
            ''' </summary>
            ''' <returns></returns>
            ''' <remarks></remarks>
            Function Get_UseQry(ByRef sortstr As String) As String Implements IConv.Get_UseQry

                Dim tmp_sql As String = ""

                sortstr = "[物件No],[送金ルール管理No],[送金先行No]"

                '抽出データの改行文字列を除去する暫定処理
                Dim tmp_midheader As String = "[物件No],[部屋No],[送金ルール管理No],[送金先行No],[送金先家主NO],[送金先口座NO],[送金率],[固定送金額]"
                Dim tmp_chgmidheader As String = EtcMethod.Get_FldnameAddReplaceMethod(tmp_midheader, True)
                '抽出データの改行文字列を除去する暫定処理

                'tmp_sql = tmp_sql & " SELECT * FROM "
                tmp_sql = tmp_sql & " SELECT " & tmp_chgmidheader & " FROM "
                tmp_sql = tmp_sql & " ( "
                tmp_sql = tmp_sql & " 	SELECT "
                tmp_sql = tmp_sql & " 		 SOKINBASE.bk_no AS [物件No] "
                tmp_sql = tmp_sql & " 		,'' AS [部屋No] "
                tmp_sql = tmp_sql & " 		,SOKINBASE.kn_no AS [送金ルール管理No] "
                tmp_sql = tmp_sql & " 		,[送金先行No] "
                tmp_sql = tmp_sql & " 		,SOKINBASE.so_no AS [送金先家主NO] "
                tmp_sql = tmp_sql & " 		,sokoza_no AS [送金先口座NO] "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN [合計金額] <> 0 THEN NULL "
                tmp_sql = tmp_sql & " 			ELSE so_rit "
                tmp_sql = tmp_sql & " 		 END AS [送金率] "
                tmp_sql = tmp_sql & " 		,yobi_kn1 AS [固定送金額]	  "
                tmp_sql = tmp_sql & " 	FROM "
                tmp_sql = tmp_sql & " 	( "
                tmp_sql = tmp_sql & " 		/*既存データを取得*/ "
                tmp_sql = tmp_sql & " 		SELECT "
                tmp_sql = tmp_sql & " 			 bk_no "
                tmp_sql = tmp_sql & " 			,kn_no "
                tmp_sql = tmp_sql & " 			,ROW_NUMBER()OVER(PARTITION BY bk_no,kn_no ORDER BY yobi_kn1 DESC,sokoza_no) AS [送金先行No] "
                tmp_sql = tmp_sql & " 			,so_no "
                tmp_sql = tmp_sql & " 			,sokoza_no "
                tmp_sql = tmp_sql & " 			,so_rit "
                tmp_sql = tmp_sql & " 			,yobi_kn1 "
                tmp_sql = tmp_sql & " 		FROM bk_sokin "
                tmp_sql = tmp_sql & " 		/*既存データを取得*/ "
                tmp_sql = tmp_sql & " 		UNION "
                tmp_sql = tmp_sql & " 		/*革命10では自動で3レコード生成されるため、2レコード目のダミーレコードを作成して結合する sta*/ "
                tmp_sql = tmp_sql & " 		SELECT DISTINCT "
                tmp_sql = tmp_sql & " 			 bk_no AS [物件No] "
                tmp_sql = tmp_sql & " 			,kn_no AS [送金ルール管理No] "
                tmp_sql = tmp_sql & " 			,2 AS [送金先行No] "
                tmp_sql = tmp_sql & " 			,so_no AS [送金先家主NO] "
                tmp_sql = tmp_sql & " 			,NULL AS [送金先口座NO] "
                tmp_sql = tmp_sql & " 			,NULL AS [送金率] "
                tmp_sql = tmp_sql & " 			,NULL AS [固定送金額]	 "
                tmp_sql = tmp_sql & " 		FROM bk_sokin AS BKS "
                tmp_sql = tmp_sql & " 		WHERE NOT EXISTS "
                tmp_sql = tmp_sql & " 		( "
                tmp_sql = tmp_sql & " 			/*2レコード目が存在するレコードのみ抽出 sta*/ "
                tmp_sql = tmp_sql & " 			SELECT * FROM "
                tmp_sql = tmp_sql & " 			( "
                tmp_sql = tmp_sql & " 				SELECT * FROM "
                tmp_sql = tmp_sql & " 				( "
                tmp_sql = tmp_sql & " 					SELECT "
                tmp_sql = tmp_sql & " 						 bk_no "
                tmp_sql = tmp_sql & " 						,kn_no "
                tmp_sql = tmp_sql & " 						,ROW_NUMBER()OVER(PARTITION BY bk_no,kn_no ORDER BY yobi_kn1 DESC,sokoza_no) AS [抽出用] "
                tmp_sql = tmp_sql & " 						,so_no "
                tmp_sql = tmp_sql & " 						,sokoza_no "
                tmp_sql = tmp_sql & " 						,so_rit "
                tmp_sql = tmp_sql & " 						,yobi_kn1 "
                tmp_sql = tmp_sql & " 					FROM bk_sokin "
                tmp_sql = tmp_sql & " 				) AS VW "
                tmp_sql = tmp_sql & " 				WHERE [抽出用] = 2 "
                tmp_sql = tmp_sql & " 			) AS VW2 "
                tmp_sql = tmp_sql & " 			/*2レコード目が存在するレコードのみ抽出 end*/ "
                tmp_sql = tmp_sql & " 		WHERE BKS.bk_no = VW2.bk_no "
                tmp_sql = tmp_sql & " 		AND   BKS.kn_no = VW2.kn_no "
                tmp_sql = tmp_sql & " 		) "
                tmp_sql = tmp_sql & " 		/*革命10では自動で3レコード生成されるため、2レコード目のダミーレコードを作成して結合する end*/ "
                tmp_sql = tmp_sql & " 		UNION "
                tmp_sql = tmp_sql & " 		/*革命10では自動で3レコード生成されるため、3レコード目のダミーレコードを作成して結合する sta*/ "
                tmp_sql = tmp_sql & " 		SELECT DISTINCT "
                tmp_sql = tmp_sql & " 			 bk_no AS [物件No] "
                tmp_sql = tmp_sql & " 			,kn_no AS [送金ルール管理No] "
                tmp_sql = tmp_sql & " 			,3 AS [送金先行No] "
                tmp_sql = tmp_sql & " 			,so_no AS [送金先家主NO] "
                tmp_sql = tmp_sql & " 			,NULL AS [送金先口座NO] "
                tmp_sql = tmp_sql & " 			,NULL AS [送金率] "
                tmp_sql = tmp_sql & " 			,NULL AS [固定送金額]	 "
                tmp_sql = tmp_sql & " 		FROM bk_sokin AS BKS "
                tmp_sql = tmp_sql & " 		WHERE NOT EXISTS "
                tmp_sql = tmp_sql & " 		( "
                tmp_sql = tmp_sql & " 			/*3レコード目が存在するレコードのみ抽出 sta*/ "
                tmp_sql = tmp_sql & " 			SELECT * FROM "
                tmp_sql = tmp_sql & " 			( "
                tmp_sql = tmp_sql & " 				SELECT * FROM "
                tmp_sql = tmp_sql & " 				( "
                tmp_sql = tmp_sql & " 					SELECT "
                tmp_sql = tmp_sql & " 						 bk_no "
                tmp_sql = tmp_sql & " 						,kn_no "
                tmp_sql = tmp_sql & " 						,ROW_NUMBER()OVER(PARTITION BY bk_no,kn_no ORDER BY yobi_kn1 DESC,sokoza_no) AS [抽出用] "
                tmp_sql = tmp_sql & " 						,so_no "
                tmp_sql = tmp_sql & " 						,sokoza_no "
                tmp_sql = tmp_sql & " 						,so_rit "
                tmp_sql = tmp_sql & " 						,yobi_kn1 "
                tmp_sql = tmp_sql & " 					FROM bk_sokin "
                tmp_sql = tmp_sql & " 				) AS VW "
                tmp_sql = tmp_sql & " 				WHERE [抽出用] = 3 "
                tmp_sql = tmp_sql & " 			) AS VW2 "
                tmp_sql = tmp_sql & " 			/*3レコード目が存在するレコードのみ抽出 end*/ "
                tmp_sql = tmp_sql & " 		WHERE BKS.bk_no = VW2.bk_no "
                tmp_sql = tmp_sql & " 		AND   BKS.kn_no = VW2.kn_no "
                tmp_sql = tmp_sql & " 		) "
                tmp_sql = tmp_sql & " 		/*革命10では自動で3レコード生成されるため、3レコード目のダミーレコードを作成して結合する end*/ "
                tmp_sql = tmp_sql & " 	) AS SOKINBASE "
                tmp_sql = tmp_sql & " 	/*金額指定の合計金額を取得し、送金率設定元とする sta*/ "
                tmp_sql = tmp_sql & " 	LEFT JOIN "
                tmp_sql = tmp_sql & " 		( "
                tmp_sql = tmp_sql & " 			SELECT bk_no,kn_no,so_no,SUM(yobi_kn1) AS 合計金額 FROM bk_sokin "
                tmp_sql = tmp_sql & " 			GROUP BY bk_no,kn_no,so_no "
                tmp_sql = tmp_sql & " 		) AS SOKIN "
                tmp_sql = tmp_sql & " 	/*金額指定の合計金額を取得し、送金率設定元とする end*/ "
                tmp_sql = tmp_sql & " 	ON  SOKINBASE.bk_no = SOKIN.bk_no "
                tmp_sql = tmp_sql & " 	AND SOKINBASE.kn_no = SOKIN.kn_no "
                tmp_sql = tmp_sql & " 	AND SOKINBASE.so_no = SOKIN.so_no "
                tmp_sql = tmp_sql & " ) AS VW "

                Return tmp_sql

            End Function

            Public Function Chk_Data(ByVal tblname As String, ByVal keyvalue As String, ByVal list As List(Of String), ByVal hash_chkbefore As Hashtable, ByRef hash_chkafter As Hashtable, ByRef conditioncnt As Integer) As Boolean Implements IConv.Chk_Data

            End Function

            Public Sub Get_BaseKey(ByVal sqlcnnv10 As SqlConnection, ByVal tblname As String, ByRef list_basedata As List(Of String)) Implements IConv.Get_BaseKey

            End Sub

            Public Function Set_Vari(sqlcnnv10 As SqlConnection, filename As String, sheetname As String, ByRef midrowcnt As Integer, ByRef cvrowcnt As Integer, ByRef conditioncnt As Integer) As Boolean Implements IConv.Set_Vari

            End Function

            Public Sub Get_ExistData(sqlcnnv10 As SqlConnection, tblname As String, ByRef list_existdata As List(Of String)) Implements IConv.Get_ExistData

            End Sub

        End Class

    End Class

#End Region

#Region "送金ルール入金項目情報"

    Public Class Hy_kanri_sorulenkin_Repository

        Public Class SubConv
            Implements IConv

            ''' <summary>
            ''' 【抽出クエリ】
            ''' </summary>
            ''' <returns></returns>
            ''' <remarks></remarks>
            Function Get_UseQry(ByRef sortstr As String) As String Implements IConv.Get_UseQry

                Dim tmp_sql As String = ""

                sortstr = "[物件No],[送金ルール管理No],[月々/契約時/更新時区分],[行NO]"

                '抽出データの改行文字列を除去する暫定処理
                Dim tmp_midheader As String = "[物件No],[部屋No],[送金ルール管理No],[月々/契約時/更新時区分],[行NO],[入金項目名],[送金率],[管理手数料率],[滞納保証有無],[送金先No]"
                Dim tmp_chgmidheader As String = EtcMethod.Get_FldnameAddReplaceMethod(tmp_midheader, True)
                '抽出データの改行文字列を除去する暫定処理

                'tmp_sql = tmp_sql & " SELECT * FROM "
                tmp_sql = tmp_sql & " SELECT " & tmp_chgmidheader & " FROM "
                tmp_sql = tmp_sql & " ( "
                tmp_sql = tmp_sql & " 	/*部屋入金項目情報から実データ抽出 sta*/ "
                tmp_sql = tmp_sql & " 	SELECT "
                tmp_sql = tmp_sql & " 		 HYKANRI.bk_no AS [物件No] "
                tmp_sql = tmp_sql & " 		,'' AS [部屋No] "
                tmp_sql = tmp_sql & " 		,BKK.kn_no AS [送金ルール管理No] "
                tmp_sql = tmp_sql & " 		,[月々/契約時/更新時区分] "
                tmp_sql = tmp_sql & " 		,ROW_NUMBER()OVER(PARTITION BY HYKANRI.bk_no,BKK.kn_no,[月々/契約時/更新時区分] ORDER BY HYKANRI.nkin_no) AS [行NO] "
                tmp_sql = tmp_sql & " 		/*,nkin_no AS [入金項目No]*/ "
                tmp_sql = tmp_sql & " 		,nkin_name AS [入金項目名] "
                tmp_sql = tmp_sql & " 		/*20160613 送金率が移行されていない現象の対応 chg sta*/ "
                tmp_sql = tmp_sql & " 		/*,[送金率]*/ "
                tmp_sql = tmp_sql & " 		,ISNULL([送金率],0) AS [送金率] "
                tmp_sql = tmp_sql & " 		/*20160613 送金率が移行されていない現象の対応 chg end*/ "
                tmp_sql = tmp_sql & " 		,[管理手数料率] "
                tmp_sql = tmp_sql & " 		,tnh_umu AS [滞納保証有無] "
                tmp_sql = tmp_sql & " 		/*,so_no AS [送金先No]*/	/*使用されていない可能性あり(画面上で入金項目毎の送金先設定箇所が不明のため)*/ "
                tmp_sql = tmp_sql & " 		,NULL  AS [送金先No] "
                tmp_sql = tmp_sql & " 	FROM "
                tmp_sql = tmp_sql & " 	( "
                tmp_sql = tmp_sql & " 		SELECT DISTINCT "
                tmp_sql = tmp_sql & " 			 HYK.bk_no "
                tmp_sql = tmp_sql & " 			/*20160725 送金ルール入金項目情報抽出クエリ修正 add*/ "
                tmp_sql = tmp_sql & " 			,BKK.kn_no "
                tmp_sql = tmp_sql & " 			,CASE "
                tmp_sql = tmp_sql & " 				WHEN HYK.nkin_kbn = 1 THEN 1 "
                tmp_sql = tmp_sql & " 				WHEN HYK.nkin_kbn = 2 THEN 2 "
                tmp_sql = tmp_sql & " 				WHEN HYK.nkin_kbn = 3 THEN 3 "
                tmp_sql = tmp_sql & " 				WHEN koteihendo_kbn = 1 AND HYK.nkin_kbn = 5 THEN 1 "
                tmp_sql = tmp_sql & " 				WHEN koteihendo_kbn = 2 AND HYK.nkin_kbn = 5 THEN 5 "
                tmp_sql = tmp_sql & " 				ELSE NULL "
                tmp_sql = tmp_sql & " 			 END AS [月々/契約時/更新時区分] "
                tmp_sql = tmp_sql & " 			,HYK.nkin_no "
                tmp_sql = tmp_sql & " 			,[最大送金率] AS [送金率] "
                tmp_sql = tmp_sql & " 			,[最大管理手数料率] AS [管理手数料率] "
                tmp_sql = tmp_sql & " 		FROM hy_kanri AS HYK "
                tmp_sql = tmp_sql & " 		/*20160725 送金ルール入金項目情報抽出クエリ修正 add*/ "
                tmp_sql = tmp_sql & " 		LEFT JOIN bk_kanri AS BKK ON HYK.bk_no = BKK.bk_no "
                tmp_sql = tmp_sql & " 		LEFT JOIN "
                tmp_sql = tmp_sql & " 		( "
                tmp_sql = tmp_sql & " 			/*最大管理手数料率・送金率をVIEW化 sta*/ "
                tmp_sql = tmp_sql & " 			SELECT DISTINCT "
                tmp_sql = tmp_sql & " 				 HYKKANRITESURITU.bk_no "
                tmp_sql = tmp_sql & " 				/*20160725 送金ルール入金項目情報抽出クエリ修正 add*/ "
                tmp_sql = tmp_sql & " 				,HYKKANRITESURITU.kn_no "
                tmp_sql = tmp_sql & " 				,HYKKANRITESURITU.nkin_no "
                tmp_sql = tmp_sql & " 				,[最大管理手数料率] "
                tmp_sql = tmp_sql & " 				,[最大送金率] "
                tmp_sql = tmp_sql & " 			FROM "
                tmp_sql = tmp_sql & " 			( "
                tmp_sql = tmp_sql & " 				/*最大管理手数料率の抽出 sta*/ "
                tmp_sql = tmp_sql & " 				SELECT "
                tmp_sql = tmp_sql & " 					 HYK.bk_no "
                tmp_sql = tmp_sql & " 					/*20160725 送金ルール入金項目情報抽出クエリ修正 add*/ "
                tmp_sql = tmp_sql & " 					,BKK.kn_no "
                tmp_sql = tmp_sql & " 					,nkin_no "
                tmp_sql = tmp_sql & " 					,MAX([管理手数料率]) AS [最大管理手数料率] "
                tmp_sql = tmp_sql & " 				FROM hy_kanri AS HYK "
                tmp_sql = tmp_sql & " 				LEFT JOIN bk_kanri AS BKK ON HYK.bk_no = BKK.bk_no "
                tmp_sql = tmp_sql & " 				LEFT JOIN "
                tmp_sql = tmp_sql & " 					( "
                tmp_sql = tmp_sql & " 						/*管理手数料率をマスタ化 sta*/ "
                tmp_sql = tmp_sql & " 						SELECT * FROM "
                tmp_sql = tmp_sql & " 						( "
                tmp_sql = tmp_sql & " 							SELECT bk_no,kn_no,1 AS [管理手数料率No],kanritesu_rit1 AS [管理手数料率] FROM bk_kanri "
                tmp_sql = tmp_sql & " 							UNION "
                tmp_sql = tmp_sql & " 							SELECT bk_no,kn_no,2 AS [管理手数料率No],kanritesu_rit2 AS [管理手数料率] FROM bk_kanri "
                tmp_sql = tmp_sql & " 							UNION "
                tmp_sql = tmp_sql & " 							SELECT bk_no,kn_no,3 AS [管理手数料率No],kanritesu_rit3 AS [管理手数料率] FROM bk_kanri "
                tmp_sql = tmp_sql & " 							UNION "
                tmp_sql = tmp_sql & " 							SELECT bk_no,kn_no,4 AS [管理手数料率No],kanritesu_rit4 AS [管理手数料率] FROM bk_kanri "
                tmp_sql = tmp_sql & " 							UNION "
                tmp_sql = tmp_sql & " 							SELECT bk_no,kn_no,5 AS [管理手数料率No],kanritesu_rit5 AS [管理手数料率] FROM bk_kanri "
                tmp_sql = tmp_sql & " 						) AS VW "
                tmp_sql = tmp_sql & " 						WHERE [管理手数料率] <> 0 "
                tmp_sql = tmp_sql & " 						/*管理手数料率をマスタ化 end*/ "
                tmp_sql = tmp_sql & " 					) AS KANRIRYOMST "
                tmp_sql = tmp_sql & " 				ON  HYK.bk_no = KANRIRYOMST.bk_no "
                tmp_sql = tmp_sql & " 				AND BKK.kn_no = KANRIRYOMST.kn_no "
                tmp_sql = tmp_sql & " 				AND HYK.kn_ritno = KANRIRYOMST.[管理手数料率No] "
                tmp_sql = tmp_sql & " 				/*20160725 送金ルール入金項目情報抽出クエリ修正 chg sta*/ "
                tmp_sql = tmp_sql & " 				/*GROUP BY HYK.bk_no,nkin_no*/ "
                tmp_sql = tmp_sql & " 				GROUP BY HYK.bk_no,BKK.kn_no,nkin_no "
                tmp_sql = tmp_sql & " 				/*20160725 送金ルール入金項目情報抽出クエリ修正 chg end*/ "
                tmp_sql = tmp_sql & " 				/*最大管理手数料率の抽出 end*/ "
                tmp_sql = tmp_sql & " 			) AS HYKKANRITESURITU "
                tmp_sql = tmp_sql & " 			LEFT JOIN "
                tmp_sql = tmp_sql & " 			( "
                tmp_sql = tmp_sql & " 				/*最大送金率の抽出 sta*/ "
                tmp_sql = tmp_sql & " 				SELECT "
                tmp_sql = tmp_sql & " 					 bk_no "
                tmp_sql = tmp_sql & " 					,nkin_no "
                tmp_sql = tmp_sql & " 					,MAX(sokin_rit) AS [最大送金率] "
                tmp_sql = tmp_sql & " 				FROM hy_kanri "
                tmp_sql = tmp_sql & " 				GROUP BY bk_no,nkin_no "
                tmp_sql = tmp_sql & " 				/*最大送金率の抽出 end*/ "
                tmp_sql = tmp_sql & " 			) AS HYKSOKINRITU "
                tmp_sql = tmp_sql & " 			ON  HYKKANRITESURITU.bk_no = HYKSOKINRITU.bk_no "
                tmp_sql = tmp_sql & " 			AND HYKKANRITESURITU.nkin_no = HYKSOKINRITU.nkin_no "
                tmp_sql = tmp_sql & " 			/*最大管理手数料率・送金率をVIEW化 end*/ "
                tmp_sql = tmp_sql & " 		) AS HYKANRISOKINTOTAL "
                tmp_sql = tmp_sql & " 		ON  HYK.bk_no = HYKANRISOKINTOTAL.bk_no "
                tmp_sql = tmp_sql & " 		/*20160725 送金ルール入金項目情報抽出クエリ修正 add*/ "
                tmp_sql = tmp_sql & " 		AND BKK.kn_no = HYKANRISOKINTOTAL.kn_no "
                tmp_sql = tmp_sql & " 		AND HYK.nkin_no = HYKANRISOKINTOTAL.nkin_no "
                tmp_sql = tmp_sql & " 	) AS HYKANRI "
                tmp_sql = tmp_sql & " 	/*20160725 送金ルール入金項目情報抽出クエリ修正 chg sta*/ "
                tmp_sql = tmp_sql & " 	/*LEFT JOIN (SELECT bk_no,kn_no,tnh_umu FROM bk_kanri) AS BKK ON HYKANRI.bk_no = BKK.bk_no*/ "
                tmp_sql = tmp_sql & " 	LEFT JOIN (SELECT bk_no,kn_no,tnh_umu FROM bk_kanri) AS BKK "
                tmp_sql = tmp_sql & " 	ON  HYKANRI.bk_no = BKK.bk_no "
                tmp_sql = tmp_sql & " 	AND HYKANRI.kn_no = BKK.kn_no "
                tmp_sql = tmp_sql & " 	/*20160725 送金ルール入金項目情報抽出クエリ修正 chg end*/ "
                tmp_sql = tmp_sql & " 	LEFT JOIN m_nkin AS MN ON HYKANRI.nkin_no = MN.nkin_no "
                tmp_sql = tmp_sql & " 	/*LEFT JOIN bk_sokin AS BKS ON BKK.bk_no = BKS.bk_no AND BKK.kn_no = BKS.kn_no*/ "
                tmp_sql = tmp_sql & " 	WHERE [月々/契約時/更新時区分] IS NOT NULL "
                tmp_sql = tmp_sql & " 	/*部屋入金項目情報から実データ抽出 end*/ "
                tmp_sql = tmp_sql & " 	/*20160928 送金ルールその他請求取得処理修正 del sta*/ "
                tmp_sql = tmp_sql & " 	/*プログラム内で自動作成する処理へ修正*/ "
                tmp_sql = tmp_sql & " 	/* "
                tmp_sql = tmp_sql & " 	UNION "
                tmp_sql = tmp_sql & " 	/*送金ルール作成時にその他請求のレコードが生成されるためダミーレコードを作成しておく sta*/ "
                tmp_sql = tmp_sql & " 	SELECT DISTINCT "
                tmp_sql = tmp_sql & " 		 HYK.bk_no AS [物件No] "
                tmp_sql = tmp_sql & " 		,'' AS [部屋No] "
                tmp_sql = tmp_sql & " 		,BKK.kn_no AS [送金ルール管理No] "
                tmp_sql = tmp_sql & " 		,7 AS [月々/契約時/更新時区分] "
                tmp_sql = tmp_sql & " 		,1 AS [行NO] "
                tmp_sql = tmp_sql & " 		/*,NULL AS [入金項目No]*/ "
                tmp_sql = tmp_sql & " 		,'挿入用' AS [入金項目名] "
                tmp_sql = tmp_sql & " 		,100 AS [送金率] "
                tmp_sql = tmp_sql & " 		,100 AS [管理手数料率] "
                tmp_sql = tmp_sql & " 		,tnh_umu AS [滞納保証有無] "
                tmp_sql = tmp_sql & " 		/*,so_no AS [送金先No]*/	/*使用されていない可能性あり(画面上で入金項目毎の送金先設定箇所が不明のため)*/ "
                tmp_sql = tmp_sql & " 		,NULL  AS [送金先No] "
                tmp_sql = tmp_sql & " 	FROM hy_kanri HYK "
                tmp_sql = tmp_sql & " 	LEFT JOIN (SELECT bk_no,kn_no,tnh_umu FROM bk_kanri) AS BKK ON HYK.bk_no = BKK.bk_no "
                tmp_sql = tmp_sql & " 	LEFT JOIN bk_sokin AS BKS ON HYK.bk_no = BKK.bk_no "
                tmp_sql = tmp_sql & " 	LEFT JOIN m_nkin AS MN ON HYK.nkin_no = MN.nkin_no "
                tmp_sql = tmp_sql & " 	/*送金ルール作成時にその他請求のレコードが生成されるためダミーレコードを作成しておく end*/ "
                tmp_sql = tmp_sql & " 	*/ "
                tmp_sql = tmp_sql & " 	/*20160928 送金ルールその他請求取得処理修正 del end*/ "
                tmp_sql = tmp_sql & " ) AS TOTAL "
                tmp_sql = tmp_sql & " /*2016.04.06 送金ルール入金/控除項目取得条件の追加 add*/ "
                tmp_sql = tmp_sql & " WHERE [送金ルール管理No] IS NOT NULL "

                Return tmp_sql

            End Function

            Public Function Chk_Data(ByVal tblname As String, ByVal keyvalue As String, ByVal list As List(Of String), ByVal hash_chkbefore As Hashtable, ByRef hash_chkafter As Hashtable, ByRef conditioncnt As Integer) As Boolean Implements IConv.Chk_Data

            End Function

            Public Sub Get_BaseKey(ByVal sqlcnnv10 As SqlConnection, ByVal tblname As String, ByRef list_basedata As List(Of String)) Implements IConv.Get_BaseKey

            End Sub

            Public Function Set_Vari(sqlcnnv10 As SqlConnection, filename As String, sheetname As String, ByRef midrowcnt As Integer, ByRef cvrowcnt As Integer, ByRef conditioncnt As Integer) As Boolean Implements IConv.Set_Vari

            End Function

            Public Sub Get_ExistData(sqlcnnv10 As SqlConnection, tblname As String, ByRef list_existdata As List(Of String)) Implements IConv.Get_ExistData

            End Sub

        End Class

    End Class

#End Region

#Region "送金ルール控除項目情報"

    Public Class Hy_kanri_sorulekojo_Repository

        Public Class SubConv
            Implements IConv

            ''' <summary>
            ''' 【抽出クエリ】
            ''' </summary>
            ''' <returns></returns>
            ''' <remarks></remarks>
            Function Get_UseQry(ByRef sortstr As String) As String Implements IConv.Get_UseQry

                Dim tmp_sql As String = ""

                sortstr = "[物件No],[送金ルール管理No],[契約時/更新時区分],[行NO]"

                '抽出データの改行文字列を除去する暫定処理
                Dim tmp_midheader As String = "[物件No],[部屋No],[送金ルール管理No],[契約時/更新時区分],[行NO],[控除入金項目名],[相殺予定フラグ],[控除額基準],[控除額],[控除額税区分],[控除対象入金項目名],[控除率],[控除率税区分],[控除率税有無],[適用税率],[立替回収または預り金],[控除税額],[送金対象フラグ],[送金対象入金項目名]"
                Dim tmp_chgmidheader As String = EtcMethod.Get_FldnameAddReplaceMethod(tmp_midheader, True)
                '抽出データの改行文字列を除去する暫定処理

                'tmp_sql = tmp_sql & " SELECT * FROM "
                tmp_sql = tmp_sql & " SELECT " & tmp_chgmidheader & " FROM "
                tmp_sql = tmp_sql & " ( "
                tmp_sql = tmp_sql & " 	SELECT "
                tmp_sql = tmp_sql & " 		 bk_no AS [物件No] "
                tmp_sql = tmp_sql & " 		,'' AS [部屋No] "
                tmp_sql = tmp_sql & " 		,kn_no AS [送金ルール管理No] "
                tmp_sql = tmp_sql & " 		,[契約時/更新時区分] "
                tmp_sql = tmp_sql & " 		,ROW_NUMBER()OVER(PARTITION BY bk_no,kn_no,[契約時/更新時区分] ORDER BY nkin_no) AS [行NO] "
                tmp_sql = tmp_sql & " 		/*,nkin_no AS [入金項目No]*/ "
                tmp_sql = tmp_sql & " 		,nkin_name AS [控除入金項目名] "
                tmp_sql = tmp_sql & " 		,sosai_umu AS [相殺予定フラグ] "
                tmp_sql = tmp_sql & " 		,2 AS [控除額基準] "
                tmp_sql = tmp_sql & " 		,sq_gak AS [控除額] "
                tmp_sql = tmp_sql & " 		,CASE "
                tmp_sql = tmp_sql & " 			WHEN sq_zeiumu = 0 THEN 1 "
                tmp_sql = tmp_sql & " 			WHEN sq_zeiumu = 1 THEN 2 "
                tmp_sql = tmp_sql & " 			ELSE 2 "
                tmp_sql = tmp_sql & " 		 END AS [控除額税区分] "
                tmp_sql = tmp_sql & " 		,'挿入用' AS [控除対象入金項目名] "
                tmp_sql = tmp_sql & " 		,NULL AS [控除率] "
                tmp_sql = tmp_sql & " 		,2 AS [控除率税区分] "
                tmp_sql = tmp_sql & " 		,0 AS [控除率税有無] "
                tmp_sql = tmp_sql & " 		,NULL AS [適用税率] "
                tmp_sql = tmp_sql & " 		,0 AS [立替回収または預り金] "
                tmp_sql = tmp_sql & " 		,0 AS [控除税額] "
                tmp_sql = tmp_sql & " 		,0 AS [送金対象フラグ] "
                tmp_sql = tmp_sql & " 		,'挿入用' [送金対象入金項目名]	 "
                tmp_sql = tmp_sql & " 	FROM "
                tmp_sql = tmp_sql & " 	( "
                tmp_sql = tmp_sql & " 		/*金額が最大の入金項目のみ抽出する sta*/ "
                tmp_sql = tmp_sql & " 		SELECT * FROM "
                tmp_sql = tmp_sql & " 		( "
                tmp_sql = tmp_sql & " 			SELECT "
                tmp_sql = tmp_sql & " 				 ROW_NUMBER()OVER(PARTITION BY bk_no,kn_no,[契約時/更新時区分],nkin_no ORDER BY sq_gak DESC) AS [抽出用] "
                tmp_sql = tmp_sql & " 				,* "
                tmp_sql = tmp_sql & " 			FROM "
                tmp_sql = tmp_sql & " 			( "
                tmp_sql = tmp_sql & " 				SELECT "
                tmp_sql = tmp_sql & " 					 HYK.bk_no "
                tmp_sql = tmp_sql & " 					,BKK.kn_no "
                tmp_sql = tmp_sql & " 					,CASE "
                tmp_sql = tmp_sql & " 						WHEN HYK.nkin_kbn = 7 AND ISNULL(HYK.yobi_si1,0) = 0 THEN 2 "
                tmp_sql = tmp_sql & " 						WHEN HYK.nkin_kbn = 7 AND ISNULL(HYK.yobi_si1,0) = 1 THEN 3 "
                tmp_sql = tmp_sql & " 						ELSE NULL "
                tmp_sql = tmp_sql & " 					 END AS [契約時/更新時区分]				 "
                tmp_sql = tmp_sql & " 					,HYK.nkin_no "
                tmp_sql = tmp_sql & " 					,nkin_name "
                tmp_sql = tmp_sql & " 					,sosai_umu "
                tmp_sql = tmp_sql & " 					,sq_gak "
                tmp_sql = tmp_sql & " 					,sq_zeiumu "
                tmp_sql = tmp_sql & " 				FROM hy_kanri AS HYK "
                tmp_sql = tmp_sql & " 				LEFT JOIN bk_kanri AS BKK ON HYK.bk_no = BKK.bk_no "
                tmp_sql = tmp_sql & " 				LEFT JOIN m_nkin AS MN ON HYK.nkin_no = MN.nkin_no "
                tmp_sql = tmp_sql & " 				LEFT JOIN bk_sokin AS BKS ON BKK.bk_no = BKS.bk_no AND BKK.kn_no = BKS.kn_no "
                tmp_sql = tmp_sql & " 			) AS VW1 "
                tmp_sql = tmp_sql & " 		) AS VW2 "
                tmp_sql = tmp_sql & " 		WHERE [抽出用] = 1 "
                tmp_sql = tmp_sql & " 		/*金額が最大の入金項目のみ抽出する end*/ "
                tmp_sql = tmp_sql & " 	) AS VW3 "
                tmp_sql = tmp_sql & " 	WHERE [契約時/更新時区分] IS NOT NULL "
                tmp_sql = tmp_sql & " ) AS TOTAL "
                tmp_sql = tmp_sql & " /*2016.04.06 送金ルール入金/控除項目取得条件の追加 add*/ "
                tmp_sql = tmp_sql & " WHERE [送金ルール管理No] IS NOT NULL "

                Return tmp_sql

            End Function

            Public Function Chk_Data(ByVal tblname As String, ByVal keyvalue As String, ByVal list As List(Of String), ByVal hash_chkbefore As Hashtable, ByRef hash_chkafter As Hashtable, ByRef conditioncnt As Integer) As Boolean Implements IConv.Chk_Data

            End Function

            Public Sub Get_BaseKey(ByVal sqlcnnv10 As SqlConnection, ByVal tblname As String, ByRef list_basedata As List(Of String)) Implements IConv.Get_BaseKey

            End Sub

            Public Function Set_Vari(sqlcnnv10 As SqlConnection, filename As String, sheetname As String, ByRef midrowcnt As Integer, ByRef cvrowcnt As Integer, ByRef conditioncnt As Integer) As Boolean Implements IConv.Set_Vari

            End Function

            Public Sub Get_ExistData(sqlcnnv10 As SqlConnection, tblname As String, ByRef list_existdata As List(Of String)) Implements IConv.Get_ExistData

            End Sub

        End Class

    End Class

#End Region

    'V7に存在しない項目

#Region "送金ルール一括借上げ額情報"

#End Region

End Namespace
